### ISSUE TITLE
GNSE UART flashing using USB to serial interfaces

### ISSUE THREAD

**Issue by elsalahy** [TheThingsIndustries/generic-node-docs#18]
#### Summary

A guide on flashing the GNSE using a USB to UART interfaces 

#### Why do we need this ?

To provide a guide on flashing the GNSE via UART 

#### What is already there? What do you see now?

Nothing

#### What is missing? What do you want to see?

A guide on flashing via UART

#### How do you propose to document this?

Add photos, links, tools/ commands

#### Can you do this yourself and submit a Pull Request?

@marnixcro will undertake this

**Comment by nejraselimovic** [comment]
@azerimaker anyone who can take this over?

**Comment by azerimaker** [comment]
@nejraselimovic I can include it in my ToDo list, but it will take some time to get back to it.

**Comment by pradeeka7** [comment]
@azerimaker now you can close this issue.
