### ISSUE TITLE
Add a link to genericnode.com in documentation

### ISSUE THREAD

**Issue by anastasiagramm** [TheThingsIndustries/generic-node-docs#24]
**Summary**

Add a link to genericnode.com page in Generic Node documentation. For instance, on [Getting a Generic Node page](https://thethingsindustries.github.io/generic-node-docs/getting-started/platform-guide/)

**Why do we need this?**

Because we are now promoting Generic Node and sharing direct links to documentation to the audience, it is important to have synergy between the genericnode.com and documentation websites both ways. So, in order to answer the question about "where to get generic node", we could lead people to the genericnode.com website and call them to join the early access program.

**What is already there? What do you see now?**

There are links to setup guides and descriptions of GN editions.

**What is missing? What do you want to see?**

Information on how to (pre-)order Generic Node.

**How do you propose to document this?**

Add the following paragraph to the [Getting a Generic Node page](https://thethingsindustries.github.io/generic-node-docs/getting-started/platform-guide/):

### Getting a device

Generic Node is currently in Beta stage. Join the early access program and become one of the first to access the node at www.genericnode.com

**Can you do this yourself and submit a Pull Request?**

No :( thank you!

**Comment by elsalahy** [comment]
@anastasiagramm this is done and deployed please check and let me know if you need anything else
