### ISSUE TITLE
Document how to make docs changes public in CONTRIBUTING.md

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsIndustries/generic-node-docs#56]
#### Summary
This is a followup issue regarding [this](https://thethingsindustries.slack.com/archives/C013TFXG3GC/p1660306591238489) discussion.

I contacted @elsalahy and he told me the process to make latest changes public is as follows:
- run  `make build.public` on `master` branch
- copy the `public` folder that gets created on `master` and make a PR that aims the `gh-pages` branch

After running `make build.public`, I also see the `doc` folder gets created automatically? Also, I couldn't make a PR that aims the `gh-pages` branch because the `.hooks` folder was lacking.

I somehow ended up with this: https://github.com/TheThingsIndustries/generic-node-docs/pull/55.

I have no idea how to proceed so @elsalahy @adriansmares can you please assist here? I can later add steps to CONTRIBUTING.md so others don't get this issue in the future.

**EDIT**: I changed the base branch on the PR from `master` to `gh-pages`, and now I see only changes related to files in the `public` folder, but I still think that changes in 148 files looks weird.

**EDIT**: We know how the process goes now, so I'll finish this.

**Comment by adriansmares** [comment]
We didn't deploy this in quite some time, so I'm not surprised that we have lots of changes. 

We can try to merge this, look at how it looks, and decide what to do next. Worst case scenario we have to revert the merge - should not be a big deal.

**Comment by elsalahy** [comment]
@nejraselimovic you just need to copy the contents of the generated public folder to gh-pages branch
To make it easier for your self with the hooks, just checkout another version of this repo so that you would have two folders one for master and one for gh-pages (deployment) and copy the generated master files to the gh pages folder and make sure to overwrite the contents.

Check out this example #49

**Comment by nejraselimovic** [comment]
Closing this as I documented steps on Discuss and we're just waiting for this process to be automated, so docs get published automatically by merging to master branch.
